sudo: required

services:
  - docker

env:
- TOXENV=py35

install:
- pip install -U tox

language: python

python: 3.5

script:
- docker-compose -f docker/docker-compose.yml run flask-template-master tox -e ${TOXENV}
