version: '2.1'
services:
  flask-template-master:
    container_name: flask-template-master
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: flask-template-master:latest
    volumes:
      - ./..:/opt/project
    ports:
      - "5000:5000"